#!/usr/bin/env python3
"""Generate CUDA kernels with several values live across a single asm block.

The post uses cudaFuncGetAttributes' *actual* register count as the x axis.
This generator only creates pressure candidates; it does not promise exact counts.
"""

from __future__ import annotations

import pathlib
import sys


def specialization(count: int) -> str:
    lines = [
        f"template <> __global__ void register_probe<{count}>(float* output, const float* input) {{",
        "  const volatile float* vin = input;",
    ]
    lines += [f"  float r{i} = 0.0f;" for i in range(count)]
    # These independent accumulators must persist across loop iterations.
    # Loading each coefficient through a volatile pointer prevents folding.
    lines.append("  for (int k = 0; k < 16; ++k) {")
    lines.append("    const float x = vin[threadIdx.x + k * blockDim.x];")
    lines += [f"    r{i} = fmaf(x, vin[{i}], r{i});" for i in range(count)]
    lines.append("  }")
    lines.append("  const float sum = " + " + ".join(f"r{i}" for i in range(count)) + ";")
    lines.append("  if (threadIdx.x == 0) output[blockIdx.x] = sum;")
    lines.append("}")
    return "\n".join(lines)


def main() -> int:
    if len(sys.argv) != 2:
        print("usage: generate_occupancy_probes.py <output-header>", file=sys.stderr)
        return 2
    path = pathlib.Path(sys.argv[1])
    path.parent.mkdir(parents=True, exist_ok=True)
    source = [
        "// Generated by generate_occupancy_probes.py; do not edit.",
        "#pragma once",
        "template <int N> __global__ void register_probe(float* output, const float* input);",
    ]
    source += [specialization(count) for count in (8, 24, 48, 80)]
    path.write_text("\n\n".join(source) + "\n")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
